/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basketgdr;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pecorelli.davide
 */
public class Interfaccia extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaccia.class.getName());
    private String personaggioSelezionato = "";
    private PannelloSfondo mioPannello;

    /**
     * Creates new form Interfaccia
     */
    public Interfaccia() {

        initComponents();

        mioPannello = new PannelloSfondo("/immagini/Darksfondo.png");
        mioPannello.add(btnselezionaKagami);
        mioPannello.add(btnselezionaKuroko);
        mioPannello.add(btnselezionaAkashi);
        mioPannello.add(btnselezionaAomine);
        mioPannello.add(btnStart);
        mioPannello.add(btnCaricaCSV);
        mioPannello.add(btnCaricaSer);
        mioPannello.add(jLabel6);
        mioPannello.add(jLabel4);
        mioPannello.add(jLabel5);
        mioPannello.add(jLabel3);
        mioPannello.add(jLabel2);
        mioPannello.add(jLabel8);
        mioPannello.add(jLabel1);
        mioPannello.add(jLabel9);
        this.setContentPane(mioPannello);
        this.revalidate();
        this.repaint();

    }

    public class PannelloSfondo extends JPanel {

        private Image immagine;

        public PannelloSfondo(String percorso) {
            // setLayout(null) se vuoi posizionare i componenti (bottoni, label) a mano con le coordinate
            this.setLayout(null);
            try {
                // Usa il percorso assoluto partendo da src (es: "/immagini/sfondo.png")
                this.immagine = new ImageIcon(getClass().getResource("/Immagini/DarkSfondo.png")).getImage();
            } catch (Exception e) {
                System.err.println("Errore: Impossibile trovare l'immagine al percorso: " + percorso);
            }
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g); // Fondamentale per pulire il pannello
            if (immagine != null) {
                Graphics2D g2d = (Graphics2D) g;

                // ATTIVA L'ALTA QUALITÀ: evita l'effetto "pixel" quando l'immagine si ingrandisce
                g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Disegna l'immagine adattandola perfettamente alla larghezza e altezza del pannello
                g2d.drawImage(immagine, 0, 0, getWidth(), getHeight(), this);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnselezionaKagami = new javax.swing.JButton();
        btnselezionaKuroko = new javax.swing.JButton();
        btnselezionaAkashi = new javax.swing.JButton();
        btnselezionaAomine = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnCaratteristicheKuroko = new javax.swing.JButton();
        btncaratteristicheKagami = new javax.swing.JButton();
        btncaratteristicheAkashi = new javax.swing.JButton();
        btncaratteristicheAomine = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCaricaSer = new javax.swing.JButton();
        btnCaricaCSV = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/Aomine.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 500, 200, 280));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/Kuroko.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 200, 310));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/Kagami.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 280, 340));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/Akashi.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 240, 330));

        btnselezionaKagami.setBackground(new java.awt.Color(204, 0, 0));
        btnselezionaKagami.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnselezionaKagami.setForeground(new java.awt.Color(255, 255, 255));
        btnselezionaKagami.setText("Select");
        btnselezionaKagami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselezionaKagamiActionPerformed(evt);
            }
        });
        getContentPane().add(btnselezionaKagami, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 780, -1, -1));

        btnselezionaKuroko.setBackground(new java.awt.Color(0, 153, 255));
        btnselezionaKuroko.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnselezionaKuroko.setForeground(new java.awt.Color(255, 255, 255));
        btnselezionaKuroko.setText("Select");
        btnselezionaKuroko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselezionaKurokoActionPerformed(evt);
            }
        });
        getContentPane().add(btnselezionaKuroko, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 790, -1, -1));

        btnselezionaAkashi.setBackground(new java.awt.Color(255, 51, 102));
        btnselezionaAkashi.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnselezionaAkashi.setForeground(new java.awt.Color(255, 255, 255));
        btnselezionaAkashi.setText("Select");
        btnselezionaAkashi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselezionaAkashiActionPerformed(evt);
            }
        });
        getContentPane().add(btnselezionaAkashi, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 790, -1, -1));

        btnselezionaAomine.setBackground(new java.awt.Color(0, 51, 153));
        btnselezionaAomine.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnselezionaAomine.setForeground(new java.awt.Color(255, 255, 255));
        btnselezionaAomine.setText("Select");
        btnselezionaAomine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselezionaAomineActionPerformed(evt);
            }
        });
        getContentPane().add(btnselezionaAomine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 790, -1, -1));

        btnStart.setBackground(new java.awt.Color(0, 0, 0));
        btnStart.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("1V1");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 860, 210, -1));

        btnCaratteristicheKuroko.setBackground(new java.awt.Color(0, 153, 255));
        btnCaratteristicheKuroko.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnCaratteristicheKuroko.setForeground(new java.awt.Color(255, 255, 255));
        btnCaratteristicheKuroko.setText("...");
        btnCaratteristicheKuroko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaratteristicheKurokoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCaratteristicheKuroko, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 790, -1, 30));

        btncaratteristicheKagami.setBackground(new java.awt.Color(204, 0, 0));
        btncaratteristicheKagami.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btncaratteristicheKagami.setForeground(new java.awt.Color(255, 255, 255));
        btncaratteristicheKagami.setText("...");
        btncaratteristicheKagami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaratteristicheKagamiActionPerformed(evt);
            }
        });
        getContentPane().add(btncaratteristicheKagami, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 780, -1, 30));

        btncaratteristicheAkashi.setBackground(new java.awt.Color(255, 51, 102));
        btncaratteristicheAkashi.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btncaratteristicheAkashi.setForeground(new java.awt.Color(255, 255, 255));
        btncaratteristicheAkashi.setText("...");
        btncaratteristicheAkashi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaratteristicheAkashiActionPerformed(evt);
            }
        });
        getContentPane().add(btncaratteristicheAkashi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 790, -1, 30));

        btncaratteristicheAomine.setBackground(new java.awt.Color(0, 51, 153));
        btncaratteristicheAomine.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btncaratteristicheAomine.setForeground(new java.awt.Color(255, 255, 255));
        btncaratteristicheAomine.setText("...");
        btncaratteristicheAomine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaratteristicheAomineActionPerformed(evt);
            }
        });
        getContentPane().add(btncaratteristicheAomine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 790, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Taiga Kagami");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 110, -1));

        btnCaricaSer.setBackground(new java.awt.Color(0, 0, 0));
        btnCaricaSer.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        btnCaricaSer.setForeground(new java.awt.Color(255, 255, 255));
        btnCaricaSer.setText("Carica ser");
        btnCaricaSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaSerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCaricaSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 870, 100, 30));

        btnCaricaCSV.setBackground(new java.awt.Color(0, 0, 0));
        btnCaricaCSV.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        btnCaricaCSV.setForeground(new java.awt.Color(255, 255, 255));
        btnCaricaCSV.setText("Carica CSV");
        btnCaricaCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaCSVActionPerformed(evt);
            }
        });
        getContentPane().add(btnCaricaCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 870, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tetsuya Kuroko");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 130, 20));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sejiuro Akashi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daiki Aomine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnselezionaAomineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselezionaAomineActionPerformed
        personaggioSelezionato = "Aomine";
        btnStart.setEnabled(true);
    }//GEN-LAST:event_btnselezionaAomineActionPerformed

    private void btnCaratteristicheKurokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaratteristicheKurokoActionPerformed

        JOptionPane.showMessageDialog(this,
                "Giocatore: Tetsuya Kuroko\n"
                + "Forza Fisica: 85\n"
                + "Abilità Speciale: Vanishing Drive\n"
                + "Ruolo: Sesto uomo\n"
                + "Descrizione:Tetsuya Kuroko sfrutta la sua scarsa presenza agendo come un'ombra che collega la squadra con passaggi fulminei e imprevedibili",
                "Caratteristiche", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnCaratteristicheKurokoActionPerformed

    private void btnselezionaKagamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselezionaKagamiActionPerformed
        personaggioSelezionato = "Kagami";
        btnStart.setEnabled(true);
    }//GEN-LAST:event_btnselezionaKagamiActionPerformed

    private void btnselezionaKurokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselezionaKurokoActionPerformed
        personaggioSelezionato = "Kuroko";
        btnStart.setEnabled(true);
    }//GEN-LAST:event_btnselezionaKurokoActionPerformed

    private void btnselezionaAkashiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselezionaAkashiActionPerformed
        personaggioSelezionato = "Akashi";
        btnStart.setEnabled(true);
    }//GEN-LAST:event_btnselezionaAkashiActionPerformed

    private void btncaratteristicheKagamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaratteristicheKagamiActionPerformed

        JOptionPane.showMessageDialog(this,
                "Giocatore: Taiga Kagami\n"
                + "Forza Fisica: 100\n"
                + "Abilità Speciale: Meteor Jam\n"
                + "Ruolo: Ala grande\n"
                + "Descrizione:Kagami Taiga ha una forza esplosiva e un'elevazione sovrumana che gli permettono di dominare il canestro",
                "Caratteristiche", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btncaratteristicheKagamiActionPerformed

    private void btncaratteristicheAkashiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaratteristicheAkashiActionPerformed

        JOptionPane.showMessageDialog(this,
                "Giocatore: Sejiuro Akashi\n"
                + "Forza Fisica: 90\n"
                + "Abilità Speciale: Ankle Breaker\n"
                + "Ruolo: Playmaker\n"
                + "Descrizione:Seijuro Akashi domina il campo con l'Occhio dell'Imperatore, prevedendo ogni mossa avversaria per annullare le difese e far cadere letteralmente i rivali ai suoi piedi",
                "Caratteristiche", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btncaratteristicheAkashiActionPerformed

    private void btncaratteristicheAomineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaratteristicheAomineActionPerformed

        JOptionPane.showMessageDialog(this,
                "Giocatore: Daiki Aomine\n"
                + "Forza Fisica: 105\n"
                + "Abilità Speciale: Formless shot\n"
                + "Ruolo: Ala grande\n"
                + "Descrizione:Daiki Aomine è l'asso della Generazione dei Miracoli, dotato di un'agilità animalesca e di un tiro informe che gli permette di segnare da qualsiasi posizione o angolazione, rendendolo virtualmente immarcabile",
                "Caratteristiche", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btncaratteristicheAomineActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        if (personaggioSelezionato.equals("")) {
            JOptionPane.showMessageDialog(this, "Seleziona un personaggio!");
            return;
        }

        Gioco partita = new Gioco();
        Nemico n = null;
        try {
            n = partita.selezionaNemico();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        Personaggio p = null;
        if (personaggioSelezionato.equals("Kagami")) {
            p = new Kagami(100, 0, 0, "Kagami", 20, false, 0, 1);
        }
        if (personaggioSelezionato.equals("Akashi")) {
            p = new Akashi(100, 0, 0, "Akashi", 25, false, 1, 1);
        }
        if (personaggioSelezionato.equals("Aomine")) {
            p = new Aomine(100, 0, 0, "Aomine", 22, false, 1, 0);
        }
        if (personaggioSelezionato.equals("Kuroko")) {
            p = new Kuroko(85, 0, 0, "Kuroko", 25, 1, 0);
        }

        new Interfaccia_Incontro(p, n).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnStartActionPerformed

    private void btnCaricaSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaSerActionPerformed

        Object[] dati = FileManager.caricaSer();

        if (dati != null) {

            Personaggio p = (Personaggio) dati[0];
            Nemico n = (Nemico) dati[1];

            Interfaccia_Incontro incontro = new Interfaccia_Incontro(p, n);
            incontro.setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Errore: File .ser non trovato o corrotto!");
        }
    }//GEN-LAST:event_btnCaricaSerActionPerformed

    private void btnCaricaCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaCSVActionPerformed

        Object[] dati = FileManager.caricaCSV();

        if (dati != null) {
            Personaggio p = (Personaggio) dati[0];
            Nemico n = (Nemico) dati[1];

            Interfaccia_Incontro incontro = new Interfaccia_Incontro(p, n);
            incontro.setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Errore: File .csv non trovato!");
        }
    }//GEN-LAST:event_btnCaricaCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaccia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaratteristicheKuroko;
    private javax.swing.JButton btnCaricaCSV;
    private javax.swing.JButton btnCaricaSer;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btncaratteristicheAkashi;
    private javax.swing.JButton btncaratteristicheAomine;
    private javax.swing.JButton btncaratteristicheKagami;
    private javax.swing.JButton btnselezionaAkashi;
    private javax.swing.JButton btnselezionaAomine;
    private javax.swing.JButton btnselezionaKagami;
    private javax.swing.JButton btnselezionaKuroko;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
