/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basketgdr;

/**
 *
 * @author Davide
 */
public class Interfaccia_Incontro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaccia_Incontro.class.getName());
    private Personaggio player;
    private Nemico nemicoCorrente;
    /**
     * Creates new form Interfaccia_Incontro
     */
    public Interfaccia_Incontro(Personaggio player, Nemico nemico) {
        initComponents();
        this.player = player;
        this.nemicoCorrente = nemico;
        
        caricaDatiPartita();
    }
    private void caricaDatiPartita() {
        // SETTAGGIO PLAYER
        lblforzaFisica.setText(String.valueOf(player.getForzaFisica()));
        lblStanchezza.setText(String.valueOf(player.getStanchezza()));
        lblSete.setText(String.valueOf(player.getSete()));
        lblSnack.setText(String.valueOf(player.getSnack()));
        lblBibita.setText(String.valueOf(player.getBibita()));
        jLabel4.setText(player.getNome());

        // SETTAGGIO NEMICO
        if (nemicoCorrente != null) {
            lblnomeNemico.setText(nemicoCorrente.getNome());
            lblforzaFisicaNemico.setText(String.valueOf(nemicoCorrente.getVita()));
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblforzaFisica = new javax.swing.JLabel();
        lblStanchezza = new javax.swing.JLabel();
        lblSete = new javax.swing.JLabel();
        btnSnack = new javax.swing.JButton();
        lblSnack = new javax.swing.JLabel();
        btnBibita = new javax.swing.JButton();
        lblBibita = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAbilitàSpeciale = new javax.swing.JButton();
        btnZone = new javax.swing.JButton();
        lblforzaFisicaNemico = new javax.swing.JLabel();
        btnPhantom = new javax.swing.JButton();
        lblnomePersonaggio = new javax.swing.JLabel();
        lblnomeNemico = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnsalvaPartita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel1.setText("Forza Fisica:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 500, 120, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel2.setText("Stanchezza:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 540, 110, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel3.setText("Sete:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 580, 60, 25);

        lblforzaFisica.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblforzaFisica.setText("0");
        getContentPane().add(lblforzaFisica);
        lblforzaFisica.setBounds(240, 510, 37, 16);

        lblStanchezza.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblStanchezza.setText("0");
        getContentPane().add(lblStanchezza);
        lblStanchezza.setBounds(240, 550, 8, 16);

        lblSete.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblSete.setText("0");
        getContentPane().add(lblSete);
        lblSete.setBounds(240, 590, 37, 16);

        btnSnack.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnSnack.setText("Snack");
        btnSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSnackActionPerformed(evt);
            }
        });
        getContentPane().add(btnSnack);
        btnSnack.setBounds(60, 630, 72, 27);

        lblSnack.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblSnack.setText("0");
        getContentPane().add(lblSnack);
        lblSnack.setBounds(240, 640, 37, 16);

        btnBibita.setText("Bibita");
        btnBibita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBibitaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBibita);
        btnBibita.setBounds(60, 670, 72, 23);

        lblBibita.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblBibita.setText("0");
        getContentPane().add(lblBibita);
        lblBibita.setBounds(240, 680, 37, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel4.setText("GIOCATORE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 70, 150, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel5.setText("AVVERSARIO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(780, 70, 160, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel6.setText("Forza Fisica");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(770, 490, 120, 25);

        btnAbilitàSpeciale.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnAbilitàSpeciale.setText("Abilità Speciale");
        btnAbilitàSpeciale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbilitàSpecialeActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbilitàSpeciale);
        btnAbilitàSpeciale.setBounds(300, 500, 150, 32);

        btnZone.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnZone.setText("ZONE");
        getContentPane().add(btnZone);
        btnZone.setBounds(300, 550, 150, 32);

        lblforzaFisicaNemico.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblforzaFisicaNemico.setText("0");
        getContentPane().add(lblforzaFisicaNemico);
        lblforzaFisicaNemico.setBounds(910, 500, 8, 16);

        btnPhantom.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnPhantom.setText("Phantom Shot");
        getContentPane().add(btnPhantom);
        btnPhantom.setBounds(300, 600, 150, 32);

        lblnomePersonaggio.setText("...");
        getContentPane().add(lblnomePersonaggio);
        lblnomePersonaggio.setBounds(180, 110, 9, 16);

        lblnomeNemico.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblnomeNemico.setText("...");
        getContentPane().add(lblnomeNemico);
        lblnomeNemico.setBounds(830, 110, 9, 20);

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 130, 230, 310);

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(760, 140, 200, 300);

        btnsalvaPartita.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnsalvaPartita.setText("Salva");
        getContentPane().add(btnsalvaPartita);
        btnsalvaPartita.setBounds(450, 20, 170, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSnackActionPerformed

    private void btnBibitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBibitaActionPerformed

    private void btnAbilitàSpecialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbilitàSpecialeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbilitàSpecialeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaccia_Incontro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbilitàSpeciale;
    private javax.swing.JButton btnBibita;
    private javax.swing.JButton btnPhantom;
    private javax.swing.JButton btnSnack;
    private javax.swing.JButton btnZone;
    private javax.swing.JButton btnsalvaPartita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblBibita;
    private javax.swing.JLabel lblSete;
    private javax.swing.JLabel lblSnack;
    private javax.swing.JLabel lblStanchezza;
    private javax.swing.JLabel lblforzaFisica;
    private javax.swing.JLabel lblforzaFisicaNemico;
    private javax.swing.JLabel lblnomeNemico;
    private javax.swing.JLabel lblnomePersonaggio;
    // End of variables declaration//GEN-END:variables
}
